config/routes.rb
Rails.application.routes.draw do
  # Root and basic pages
  root 'home#index'
  get 'apply', to: 'home#apply', as: :apply

  # Sponsor dashboard
  get 'sponsor_dashboard/index'
  resource :sponsor, only: %i[show edit update]

  # Public check-in (token-based)
  get  'checkin', to: 'checkins#new',    as: :checkin
  post 'checkin', to: 'checkins#create', as: :perform_checkin

  # Resumes
  resources :resumes, only: %i[index show edit update destroy] do
    member { get :download }
  end

  # Events & RSVPs
  resources :events, only: %i[index show] do
    resource :rsvp, only: %i[create update], controller: 'event_rsvps'
  end

  # Users & their resumes
  resources :users do
    resource :resume, only: %i[new create show edit update destroy]
  end

  # Role applications - users can create/view their own, admins can view all
  resources :role_applications, only: %i[index new create show edit update]

  # Admin authentication (Devise + OmniAuth)
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }

  devise_scope :admin do
    get 'admins/sign_in',  to: 'admins/sessions#new',     as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  # Admin Panel
  namespace :admin_panel do
    root to: 'dashboard#index'

    get 'dashboard',   to: 'dashboard#index'
    get 'leaderboard', to: 'dashboard#leaderboard'

    resources :events
    resources :attendance_links, only: %i[new create]
    resources :organizational_roles

    resources :role_applications, only: %i[index show destroy] do
      patch :update_status, on: :member
    end

    resources :sponsors do
      resources :logo_placements, except: %i[index]
      member do
        get   :assign_users
        patch :update_users
        delete :remove_logo
      end
    end

    resources :design_updates
  end
end

app/models/admin_panel.rb
module AdminPanel
  def self.table_name_prefix
    'admin_panel_'
  end
end

app/models/admin_panel/logo_placement.rb
module AdminPanel
  class LogoPlacement < ApplicationRecord
    belongs_to :sponsor, class_name: 'Sponsor'

    validates :page_name, presence: true
    validates :section, presence: true
    validates :displayed, inclusion: { in: [true, false] }
  end
end

app/controllers/admin_panel/attendance_links_controller.rb
module AdminPanel
  class AttendanceLinksController < AdminPanel::BaseController
    def new
      @events = Event.future_events.order(:event_date)
    end

    def create
      event = Event.find(params.require(:event_id))
      token = event.signed_id(purpose: 'checkin', expires_in: 30.minutes)
      link  = checkin_url(token: token)

      redirect_to admin_panel_events_path, notice: "Attendance link created: #{link}"
    end
  end
end

app/controllers/admin_panel/base_controller.rb
module AdminPanel
  class BaseController < ApplicationController
    before_action :ensure_admin_user
  end
end

app/controllers/admin_panel/dashboard_controller.rb
module AdminPanel
  class DashboardController < AdminPanel::BaseController
    def index
      @total_users = User.count
      @total_events = Event.count
      @upcoming_events = Event.where('event_date >= ?', Time.current).order(:event_date).limit(5)
      @recent_events = Event.order(created_at: :desc).limit(5)
      @resume_count = Resume.count
      @sponsor_download_stats = ResumeDownload.sponsor_statistics
    end

    def leaderboard
      @leaders = User.order(points: :desc, last_name: :asc, first_name: :asc).limit(100)
    end
  end
end

app/controllers/admin_panel/design_updates_controller.rb
# app/controllers/admin_panel/design_updates_controller.rb
module AdminPanel
  class DesignUpdatesController < AdminPanel::BaseController
    before_action :set_design_update, only: %i[show edit update destroy]

    def index
      @design_updates = DesignUpdate.recent
    end

    def show; end

    def new
      @design_update = DesignUpdate.new
    end

    def edit; end

    def create
      @design_update = DesignUpdate.new(design_update_params)
      if @design_update.save
        redirect_to admin_panel_design_updates_path,
                    notice: 'Design update was successfully created.'
      else
        render :new, status: :unprocessable_content
      end
    end

    def update
      if @design_update.update(design_update_params)
        redirect_to admin_panel_design_updates_path,
                    notice: 'Design update was successfully updated.'
      else
        render :edit, status: :unprocessable_content
      end
    end

    def destroy
      @design_update.destroy
      redirect_to admin_panel_design_updates_path,
                  notice: 'Design update was successfully deleted.'
    end

    private

    def set_design_update
      @design_update = DesignUpdate.find(params[:id])
    end

    def design_update_params
      params.require(:design_update).permit(
        :title,
        :update_date,
        :pdf_file
      )
    end
  end
end

app/controllers/admin_panel/events_controller.rb
module AdminPanel
  class EventsController < AdminPanel::BaseController
    before_action :find_event, only: %i[show edit update destroy]

    def index
      @upcoming_events = Event.future_events.order(:event_date)
      @past_events = Event.past_events.order(event_date: :desc)
    end

    def show
      load_rsvp_data
      load_attendance_data
    end

    def new
      @event = Event.new
    end

    def edit; end

    def create
      @event = Event.new(event_parameters)

      if @event.save
        redirect_to [:admin_panel, @event], notice: 'Event created successfully!'
      else
        render :new, status: :unprocessable_content
      end
    end

    def update
      if @event.update(event_parameters)
        redirect_to [:admin_panel, @event], notice: 'Event updated successfully!'
      else
        render :edit, status: :unprocessable_content
      end
    end

    def destroy
      @event.destroy
      redirect_to admin_panel_events_path, notice: 'Event deleted successfully!'
    end

    private

    def find_event
      @event = Event.find(params[:id])
    end

    def event_parameters
      params.require(:event).permit(:title, :description, :event_date, :location, :capacity, :attendance_points,
                                    :is_public, organizational_role_ids: [])
    end

    def load_rsvp_data
      rsvp_user = admin_signed_in? ? User.find_by(google_uid: current_admin.uid) : nil
      @rsvp = rsvp_user ? EventRsvp.find_by(event: @event, user: rsvp_user) : nil

      @yes_count = EventRsvp.where(event: @event, status: 'yes').count
      @no_count = EventRsvp.where(event: @event, status: 'no').count
      @maybe_count = EventRsvp.where(event: @event, status: 'maybe').count
      @rsvps = EventRsvp.includes(:user).where(event: @event).order(created_at: :asc)
    end

    def load_attendance_data
      @attendances = Attendance.includes(:user).where(event: @event).order(checked_in_at: :asc)
      @attended_count = @attendances.size
      @total_rsvps_yes = @yes_count
    end
  end
end

app/controllers/admin_panel/logo_placements_controller.rb
module AdminPanel
  class LogoPlacementsController < BaseController
    before_action :set_sponsor
    before_action :set_logo_placement, only: %i[ show edit update destroy ]

    def show; end

    def new
      @logo_placement = @sponsor.logo_placements.new
    end

    def edit; end

    def create
      @logo_placement = @sponsor.logo_placements.new(logo_placement_params)

      if @logo_placement.save
        redirect_to admin_panel_sponsor_path(@sponsor),
                    notice: 'Logo placement was successfully created.',
                    status: :see_other
      else
        render :new, status: :unprocessable_content
      end
    end

    def update
      if @logo_placement.update(logo_placement_params)
        redirect_to admin_panel_sponsor_path(@sponsor),
                    notice: 'Logo placement was successfully updated.',
                    status: :see_other
      else
        render :edit, status: :unprocessable_content
      end
    end

    def destroy
      @logo_placement.destroy
      redirect_to admin_panel_sponsor_path(@sponsor),
                  notice: 'Logo placement was successfully destroyed.'
    end

    private

    def set_sponsor
      @sponsor = Sponsor.find(params[:sponsor_id])
    end

    def set_logo_placement
      @logo_placement = @sponsor.logo_placements.find(params[:id])
    end

    def logo_placement_params
      params.require(:logo_placement).permit(:page_name, :section, :displayed)
    end
  end
end

app/controllers/admin_panel/organizational_roles_controller.rb
module AdminPanel
  class OrganizationalRolesController < BaseController
    before_action :set_organizational_role, only: %i[show edit update destroy]

    # GET /admin_panel/organizational_roles
    def index
      @organizational_roles = OrganizationalRole.all
    end

    # GET /admin_panel/organizational_roles/1
    def show; end

    # GET /admin_panel/organizational_roles/new
    def new
      @organizational_role = OrganizationalRole.new
    end

    # GET /admin_panel/organizational_roles/1/edit
    def edit; end

    # POST /admin_panel/organizational_roles
    def create
      @organizational_role = OrganizationalRole.new(organizational_role_params)

      respond_to do |format|
        if @organizational_role.save
          handle_successful_create(format)
        else
          handle_failed_create(format)
        end
      end
    end

    # PATCH/PUT /admin_panel/organizational_roles/1
    def update
      respond_to do |format|
        if @organizational_role.update(organizational_role_params)
          format.html do
            redirect_to admin_panel_organizational_role_path(@organizational_role),
                        notice: 'Organizational role was successfully updated.'
          end
          format.json do
            render :show, status: :ok, location: admin_panel_organizational_role_path(@organizational_role)
          end
        else
          format.html { render :edit, status: :unprocessable_content }
          format.json { render json: @organizational_role.errors, status: :unprocessable_content }
        end
      end
    end

    # DELETE /admin_panel/organizational_roles/1
    def destroy
      @organizational_role.destroy!

      respond_to do |format|
        format.html do
          redirect_to admin_panel_organizational_roles_path, notice: 'Organizational role was successfully destroyed.',
                                                             status: :see_other
        end
        format.json { head :no_content }
      end
    end

    private

    def set_organizational_role
      @organizational_role = OrganizationalRole.find(params[:id])
    end

    def organizational_role_params
      params.require(:organizational_role).permit(:name, :description, :question_1, :question_2, :question_3)
    end

    def handle_successful_create(format)
      format.html do
        redirect_to admin_panel_organizational_role_path(@organizational_role),
                    notice: 'Organizational role was successfully created.'
      end
      format.json { render :show, status: :created, location: @organizational_role }
    end

    def handle_failed_create(format)
      format.html { render_new_or_error }
      format.json { render json: @organizational_role.errors, status: :unprocessable_content }
    end

    def render_new_or_error
      if lookup_context.exists?('new', controller_path)
        render :new, status: :unprocessable_content
      else
        render plain: @organizational_role.errors.full_messages.join(', '), status: :unprocessable_content
      end
    end
  end
end

app/controllers/admin_panel/role_applications_controller.rb
require 'csv'

module AdminPanel
  class RoleApplicationsController < BaseController
    before_action :set_role_application, only: %i[show destroy update_status]

    # rubocop:disable Metrics/AbcSize
    def index
      @role_applications = RoleApplication.includes(:user, :organizational_role)

      # Filter by status if provided
      if params[:status].present?
        selected_statuses = params[:status].select { |_k, v| v == '1' }.keys
        @role_applications = @role_applications.where(status: selected_statuses) if selected_statuses.any?
      end

      @role_applications = @role_applications.order(created_at: :desc)

      respond_to do |format|
        format.html
        format.csv do
          send_data generate_csv(@role_applications),
                    filename: "role_applications_#{Time.zone.today}.csv",
                    type: 'text/csv'
        end
      end
    end
    # rubocop:enable Metrics/AbcSize

    def show
      # Display full application details
    end

    def update_status
      if @role_application.update(status: params.dig(:role_application, :status))
        redirect_to admin_panel_role_applications_path, notice: 'Status updated successfully.'
      else
        redirect_to admin_panel_role_applications_path, alert: 'Failed to update status.'
      end
    end

    def destroy
      @role_application.destroy!
      redirect_to admin_panel_role_applications_path, notice: 'Application was successfully deleted.'
    end

    private

    def set_role_application
      @role_application = RoleApplication.find(params[:id])
    end

    def generate_csv(applications)
      CSV.generate(headers: true) do |csv|
        csv << csv_headers
        applications.each { |app| csv << csv_row(app) }
      end
    end

    def csv_headers
      [
        'Applicant Name', 'Email', 'Role', 'Status',
        'Submitted Date', 'Last Updated',
        'Question 1', 'Answer 1', 'Question 2', 'Answer 2', 'Question 3', 'Answer 3'
      ]
    end

    # rubocop:disable Metrics/AbcSize
    def csv_row(app)
      [
        "#{app.user.first_name} #{app.user.last_name}",
        app.user.email,
        app.organizational_role.name,
        app.status.humanize,
        app.created_at.strftime('%Y-%m-%d %H:%M'),
        app.updated_at.strftime('%Y-%m-%d %H:%M'),
        app.organizational_role.question_1 || '',
        app.answer_1 || '',
        app.organizational_role.question_2 || '',
        app.answer_2 || '',
        app.organizational_role.question_3 || '',
        app.answer_3 || ''
      ]
    end
    # rubocop:enable Metrics/AbcSize
  end
end

app/controllers/admin_panel/sponsors_controller.rb
module AdminPanel
  class SponsorsController < BaseController
    before_action :set_sponsor, only: %i[show edit update destroy assign_users update_users remove_logo]

    def index
      @sponsors = Sponsor.all.order(:company_name)
    end

    def show; end

    def new
      @sponsor = Sponsor.new
    end

    def edit; end

    def create
      @sponsor = Sponsor.new(sponsor_params)
      if @sponsor.save
        redirect_to admin_panel_sponsor_path(@sponsor), notice: 'Sponsor was successfully created.'
      else
        render :new
      end
    end

    def update
      if @sponsor.update(sponsor_params)
        redirect_to admin_panel_sponsor_path(@sponsor), notice: 'Sponsor was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      if @sponsor.default_sponsor?
        redirect_to admin_panel_sponsors_path,
                    alert: 'Cannot delete the default sponsor.'
        return
      end

      @sponsor.destroy
      redirect_to admin_panel_sponsors_path,
                  notice:
                  'Sponsor was successfully deleted. Associated users were moved to the default sponsor.'
    end

    def remove_logo
      if @sponsor.logo.attached?
        @sponsor.logo.purge
        redirect_to edit_admin_panel_sponsor_path(@sponsor), notice: 'Logo was successfully removed.'
      else
        redirect_to edit_admin_panel_sponsor_path(@sponsor), alert: 'No logo to remove.'
      end
    end

    def assign_users
      @available_users = User.where(role: 'sponsor')
      @assigned_users = @sponsor.users
    end

    def update_users
      user_ids = extract_user_ids
      AdminPanel::SponsorUserAssigner.new(@sponsor, user_ids).call
      redirect_success
    rescue StandardError => e
      redirect_failure(e)
    end

    private

    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    def sponsor_params
      params.require(:sponsor).permit(
        :company_name,
        :website,
        :tier,
        :contact_email,
        :phone_number,
        :company_description,
        :resume_access,
        :logo
      )
    end

    def extract_user_ids
      params.dig(:sponsor, :user_ids)&.reject(&:blank?) || []
    end

    def redirect_success
      redirect_to admin_panel_sponsor_path(@sponsor),
                  notice: "Users updated successfully. #{@sponsor.users.count} user(s) assigned."
    end

    def redirect_failure(exception)
      redirect_to assign_users_admin_panel_sponsor_path(@sponsor),
                  alert: "Error updating users: #{exception.message}"
    end
  end
end

app/helpers/admin_panel/dashboard_helper.rb
module AdminPanel
  module DashboardHelper
  end
end

app/helpers/admin_panel/design_updates_helper.rb
module AdminPanel
  module DesignUpdatesHelper
  end
end

app/helpers/admin_panel/events_helper.rb
module AdminPanel
  module EventsHelper
  end
end

app/helpers/admin_panel/logo_placements_helper.rb
module AdminPanel
  module LogoPlacementsHelper
  end
end

app/helpers/admin_panel/sponsors_helper.rb
module AdminPanel
  module SponsorsHelper
  end
end

app/views/admin_panel/dashboard/index.html.erb
<div class="admin-dashboard-page">
  <h1>Admin Dashboard</h1>
  <p class="page-subtitle">Welcome to the admin control panel</p>

  <!-- Stats Overview -->
  <div class="stats-overview">
    <div class="stat-card">
      <div class="stat-value"><%= @total_users %></div>
      <div class="stat-label">Total Users</div>
    </div>
    <div class="stat-card">
      <div class="stat-value"><%= @total_events %></div>
      <div class="stat-label">Total Events</div>
    </div>
    <div class="stat-card">
      <div class="stat-value"><%= @resume_count %></div>
      <div class="stat-label">Resumes</div>
    </div>
    <div class="stat-card">
      <div class="stat-value"><%= @total_users > 0 ? (@resume_count.to_f / @total_users * 100).round(0) : 0 %>%</div>
      <div class="stat-label">Resume Coverage</div>
    </div>
  </div>

  <!-- Main Dashboard Grid -->
  <div class="dashboard-grid">
    <!-- Resume Overview -->
    <div class="dashboard-card">
      <h2>Resume Overview</h2>
      <h3>Sponsor Download Statistics</h3>
      <% if @sponsor_download_stats&.any? %>
        <table class="sponsor-stats-table">
          <thead>
            <tr>
              <th>Sponsor Name</th>
              <th>Email</th>
              <th>Downloads</th>
            </tr>
          </thead>
          <tbody>
            <% @sponsor_download_stats.each do |stat| %>
              <tr>
                <td><%= "#{stat.first_name} #{stat.last_name}" %></td>
                <td><%= stat.email %></td>
                <td><%= stat.download_count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>No sponsor downloads recorded yet.</p>
      <% end %>
    </div>

    <!-- Admin Information -->
    <div class="dashboard-card admin-info-card">
      <h2>Admin Information</h2>
      <% if admin_signed_in? %>
        <p><strong>Status:</strong> Logged in as admin</p>
        <p><strong>Name:</strong> <%= current_admin.try(:full_name) || "Not available" %></p>
        <p><strong>Email:</strong> <%= current_admin.try(:email) || "Not available" %></p>
      <% else %>
        <p><strong>Status:</strong> Not logged in</p>
      <% end %>
    </div>
  </div>

  <!-- Quick Actions -->
  <div class="dashboard-card">
    <h2>Quick Actions</h2>
    <div class="quick-actions-grid">
      <%= link_to "Manage Users", users_path %>
      <%= link_to "Manage Events", admin_panel_events_path %>
      <%= link_to "Manage Organizational Roles", admin_panel_organizational_roles_path %>
      <%= link_to "Attendance Leaderboard", admin_panel_leaderboard_path %>
      <%= link_to "Review Applications", admin_panel_role_applications_path %>
      <%= link_to "View Resumes", resumes_path %>
      <%= link_to "Manage Sponsors", admin_panel_sponsors_path %>
      <%= link_to "Design Updates", admin_panel_design_updates_path %>
      <%= link_to "Documentation", "https://drive.google.com/drive/folders/1gctou5bVILxFghL-b4494k7JZaq7psUT?usp=sharing", target: "_blank", rel: "noopener noreferrer" %>
    </div>
  </div>

  <!-- Footer -->
  <div style="text-align: center; margin-top: var(--space-lg); padding-top: var(--space-md); border-top: 1px solid var(--color-border);">
    <%= button_to "Back to Home", root_path, method: :get, class: "btn btn-outline" %>
  </div>
</div>

app/views/admin_panel/dashboard/leaderboard.html.erb
<div class="admin-leaderboard-page">
  <div class="page-header">
    <h1>Attendance Leaderboard</h1>
  </div>

  <% if @leaders.any? %>
    <div class="leaderboard-table-container">
      <table class="leaderboard-table">
        <thead>
          <tr>
            <th class="rank-column">#</th>
            <th>Name</th>
            <th>Email</th>
            <th class="points-column">Points</th>
          </tr>
        </thead>
        <tbody>
          <% @leaders.each_with_index do |user, idx| %>
            <tr class="<%= 'top-three' if idx < 3 %>">
              <td class="rank-cell rank-<%= idx + 1 %>">
                <span class="rank-number"><%= idx + 1 %></span>
              </td>
              <td class="name-cell"><%= [user.first_name, user.last_name].compact.join(' ') %></td>
              <td class="email-cell"><%= user.email %></td>
              <td class="points-cell"><%= user.points %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="empty-state">
      <p>No users yet.</p>
    </div>
  <% end %>

  <div class="page-footer">
    <%= link_to 'Back to Admin Dashboard', admin_panel_root_path, class: 'btn btn-outline' %>
    <%= link_to 'Manage Events', admin_panel_events_path, class: 'btn btn-primary' %>
  </div>
</div>